[book]
authors = ["Jared Cosulich", "Nod Labs"]
language = "en"
multilingual = false
src = "src"
title = "Move It All - A catch-all for navigating the Move language."
description = "Move It All is an attempt to bring as many resources, questions, best-practices, tips, and tricks about the Move language into one place."

[output.html]
mathjax-support = true
site-url = "/move-it-all/"
git-repository-url = "https://github.com/jaredcosulich/move_it_all/tree/main"
edit-url-template = "https://github.com/jaredcosulich/move_it_all/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"